defaults:
  - preprocessor: preprocessor
  - models: tree # change later
  - tuning: nn


model_type: "nn"  # nn, tree, rf, xgboost, etc.
random_state: 42
batch_size: 64
experiment_name: network_security


