artifact_location: /home/marcos/Escritorio/AI-prod/AI-Driven-Network-Security/notebooks/../sqlite:/mlflow.db/0
creation_time: 1760138509605
experiment_id: '0'
last_update_time: 1760138509605
lifecycle_stage: active
name: Default
